---
title: "sentiment_art"
author: "Maxwell"
date: "4/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(generativeart)
library(gutenbergr)
library(tidytext)

```

```{r}
# Color scraping and setup
library(tidyverse)
library(rvest)
library(httr)

url <- "https://en.wikipedia.org/wiki/List_of_colors:_A%E2%80%93F"
tables <- url %>%
  read_html() %>%
  html_nodes(css = "table")
colors1 <- html_table(tables[[1]], fill = TRUE)

url <- "https://en.wikipedia.org/wiki/List_of_colors:_G%E2%80%93M"
tables <- url %>%
  read_html() %>%
  html_nodes(css = "table")
colors2 <- html_table(tables[[1]], fill = TRUE)

url <- "https://en.wikipedia.org/wiki/List_of_colors:_N%E2%80%93Z"
tables <- url %>%
  read_html() %>%
  html_nodes(css = "table")
colors3 <- html_table(tables[[1]], fill = TRUE)

colors_scrape <- rbind(colors1, colors2, colors3) %>%
  mutate(Name = str_to_lower(Name, locale = "en"),
         Name = str_replace(Name, " \\s*\\([^\\)]+\\)", "")) %>%
  distinct(Name, .keep_all = TRUE)

colors <- colors_scrape %>%
  select(Name) 

colors_all <- colors %>%
  summarise(Name = paste0(Name, collapse = "|")) %>%
  as.character(expression())

colors_all <- paste0("\\b(", colors_all, ")\\b")

```

```{r}
# Text set up

# give me a gutenburg text number -- this is because the function kept breaking

text_num <- 215

# pretty ones: 7462

# gen art function from gutenberg

library(gutenbergr)
library(tidytext)

text <- gutenberg_download(text_num) %>%
  mutate(text = str_to_lower(text, locale = "en"))

afinn <- get_sentiments("afinn")

text_afinn <- text %>%
  unnest_tokens(output = word, input = text, token = "words") %>%
  count(word, sort = TRUE) %>%
  inner_join(afinn, by = "word") %>% 
  mutate(prob = n/sum(n)) %>%
  arrange(desc(n)) 

text_neg <- text_afinn %>%
  filter(value < 0) %>%
  arrange(desc(n))

text_pos <- text_afinn %>%
  filter(value > 0) %>%
  arrange(desc(n))

# R's seed will only accept values between 1-10000, that's the purpose of *10000
senti <- sum(text_afinn$n*text_afinn$value)/sum(text_afinn$n) * 10000

senti_pos <- sum(text_pos$n*text_pos$value)/sum(text_pos$n)

senti_neg <- sum(text_neg$n*text_neg$value)/sum(text_neg$n)

senti <- abs(round(senti))

set.seed(senti)
```

```{r}
# Colors from text
# Note -- need to figure out how to get tan and red to play nicely and only show up when it's the actual color

text_grammed <- text %>%
  unnest_tokens(output = word, input = text,
  token = "ngrams", n = 3)

colors_parsed <- text_grammed %>%
  mutate(Name = str_extract(word, pattern = colors_all)) %>%
  drop_na() %>%
  select(Name)

colors_counted <- colors_parsed %>%
  group_by(Name) %>%
  count() %>%
  ungroup() %>%
  mutate(prob = n/sum(n)) %>%
  arrange(desc(n))
  
colors_final <- left_join(colors_counted, colors_scrape, by = "Name") %>%
  select(Name, `Hex(RGB)`, n, prob) %>%
  rename(Hex = `Hex(RGB)`) 

```

```{r}
# Generative Art
library(generativeart)

IMG_DIR <- "img_new/"
IMG_SUBDIR <- "everything/"
IMG_SUBDIR2 <- "handpicked/"
IMG_PATH <- paste0(IMG_DIR, IMG_SUBDIR)

LOGFILE_DIR <- "logfile/"
LOGFILE <- "logfile.csv"
LOGFILE_PATH <- paste0(LOGFILE_DIR, LOGFILE)

# directory
generativeart::setup_directories(IMG_DIR, IMG_SUBDIR, IMG_SUBDIR2, LOGFILE_DIR)

# Setting colors
color_background <- colors_final[2, 2]
color_background <- color_background %>%
  as.character(expression())

color_main <- colors_final[1, 2]
color_main <- color_main %>%
  as.character(expression())

# Formula:
my_formula <- list(
  x = quote(runif(1, -1, 1) * x_i^2 - senti_neg * sin(y_i^2)),
  y = quote(runif(1, -1, 1) * y_i^2 - senti_pos * cos(x_i^2))
)

# Generating image
generate_img_fix <- function(formula, senti, polar = FALSE, filetype = "png", ...) {
    set.seed(senti)
    file_name <- generate_filename(senti, filetype)
    logfile <- check_logfile_existence()
    logfile <- generate_logfile_entry(logfile, formula, senti, file_name)
    df <- generate_data(formula)
    plot <- generate_plot(df, file_name, polar, filetype, ...)
}

generate_img_fix(formula = my_formula, 
                 senti, 
                 polar = TRUE, 
                 filetype = "png", 
                 color = color_main, 
                 background_color = color_background)

set.seed(senti)

title <- sample_n(text_afinn, 3, replace = TRUE, weight = prob) %>%
  select(word) %>%
  print()
```

```{r}

# Not my code go to: https://jean.fan/art-with-code/portfolio/20180720_mondrian/

composition <- function(
  width=100, height=100,
  minDistApart=round(min(width, height)/20),
  fixedLines=FALSE, seed=NA) {

  if(!is.na(senti)) {
    set.seed(senti)
  }

  # set colors; red, yellow, blue, black, white
  colors <- c(colors_final$Hex)
  # more likely to sample white, least likely to sample black
  p <- c(colors_final$prob)

  # random number of horizontal and vertical lines
  # more likely to sample lower number
  nLinesX <- sample(2:floor(width/minDistApart), 1, p=1/(2:floor(width/minDistApart)))
  # make sure lines are not too close together
  x <- sample(1:floor(width/minDistApart), nLinesX)*minDistApart
  x <- sort(x)
  nLinesY <- sample(2:floor(height/minDistApart), 1, p=1/(2:floor(height/minDistApart)))
  y <- sample(1:floor(height/minDistApart), nLinesY)*minDistApart
  y <- sort(y)

  # set line width
  if(fixedLines) {
    lineWidthX <- rep(round(min(width, height)/20), nLinesX)
    lineWidthY <- rep(round(min(width, height)/20), nLinesY)
  } else {
    lineWidthX <- sample(round(min(width, height)/20):round(min(width, height)/5), nLinesX, replace=TRUE)
    lineWidthY <- sample(round(min(width, height)/20):round(min(width, height)/5), nLinesY, replace=TRUE)
  }

  # randomly decide whether to go to edge
  if(sample(c(TRUE, FALSE), 1)) {
    x <- c(0, x)
    lineWidthX <- c(0, lineWidthX)
  }
  if(sample(c(TRUE, FALSE), 1)) {
    x <- c(x, width)
    lineWidthX <- c(lineWidthX, 0)
  }
  if(sample(c(TRUE, FALSE), 1)) {
    y <- c(0, y)
    lineWidthY <- c(0, lineWidthY)
  }
  if(sample(c(TRUE, FALSE), 1)) {
    y <- c(y, height)
    lineWidthY <- c(lineWidthY, 0)
  }

  # plot
  plot(NULL, xlim=c(0, width), ylim=c(0, height), axes=FALSE, frame.plot=TRUE, xlab='', ylab='', xaxs = "i", yaxs = "i")
  # add lines
  abline(v=x, lwd=lineWidthX)
  abline(h=y, lwd=lineWidthY)
  # add colored polygons
  for(i in 1:(length(y))) {
    for(j in 1:(length(x))) {
      randColor <- sample(colors, 1, prob=p) # random color
      k = sample(y[-i], 1)
      l = sample(x[-j], 1)
      polygon(c(x[j], l, l, x[j]), c(y[i], y[i], k, k), col=randColor, border='black', lwd = round(min(width, height)/20))
    }
  }

}

# Runner
par(mfrow=c(1,1), mar=rep(1,4))
composition(fixedLines=TRUE, seed=NA)
```

```{r}
# https://jean.fan/art-with-code/portfolio/20180721_tunnel/

library(grid) 

## Number of frames
N <- 500
## Number of colors
k <- 100
## N/k is number of times color palette will repeat

## Some sample colors
colors <- rep(rainbow(k, s=0.8), N/k)
#colors <- rep(colorRampPalette(c('orange','yellow', 'darkorange'))(k), N/k)
#colors <- rep(colorRampPalette(c('white', 'pink', 'white', 'lightblue', 'white'))(k), N/k)
#colors <- colorRampPalette(c('beige', 'forestgreen', 'darkgreen'))(N)

## Draw background
dev.new()
pushViewport(viewport(width=1, height=1, angle=0))
grid.rect(gp = gpar(col = NA, fill = colors[1]))

## Scale viewport and rotate
for(i in 2:N){
  ## Optionally try increasing the angle or increasing the scale rate
  pushViewport(viewport(width=0.99, height=0.99, angle=1))
  # Optionally try: grid.circle(), grid.roundedrect()
  grid.rect(
    # Optionally shift: x = 0, y = 1,
    gp = gpar(col = NA, fill = colors[i])
  )
}
```

```{r}
# trying to make something that works vaguely like: https://datatricks.co.uk/the-hidden-art-in-pi

# Unsorted affinity, so the book from start to finish
text_afinn_unsort <- text %>%
  unnest_tokens(output = word, input = text, token = "words") %>%
  inner_join(afinn, by = "word") 

text_unsort_simp <- text_afinn_unsort %>%
  mutate(value = case_when(value == 1 ~ 1,
                           value == 2 ~ 2,
                           value == -1 ~ -1,
                           value == -2 ~ -2,
                           value %in% 3:5 ~ 3,
                           value %in% -3:-5 ~ -3))

book_coords <- text_unsort_simp %>%
  select(value) %>%
    mutate(sign = sign(value),
         x_coord = cumsum(sign),
         y_coord = cumsum(value))

book_coords_7deg <- text_unsort_simp %>%
  mutate(x_coord = cumsum(case_when(value == 1 ~ .78,
                             value == 2 ~ .97,
                             value == 3 ~ .43,
                             value == -1 ~ -.78,
                             value == -2 ~ -.97,
                             value == -3 ~ -.43)),
         y_coord = cumsum(case_when(value == 1 ~ .62,
                             value == 2 ~ -.22,
                             value == 3 ~ -.9,
                             value == -1 ~ .62,
                             value == -2 ~ -.22,
                             value == -3 ~ -.9)),
         color_val = row_number())

ggplot(data = book_coords_7deg, mapping = aes(x = x_coord, y = y_coord, color = color_val)) +
  geom_point(size = .1) +
  scale_color_continuous(high = "dark red", low = "white") +
  theme(line = element_blank(),
        text = element_blank(),
        title = element_blank(),
        panel.background = element_rect(fill = "black",
                                colour = "black",
                                size = 0.5, linetype = "solid"))

```


```{r}
# Using proportions of words -- randomly sampled
text_afinn_simp <- text_afinn %>%
  mutate(value = case_when(value == 1 ~ 1,
                           value == 2 ~ 2,
                           value == -1 ~ -1,
                           value == -2 ~ -2,
                           value %in% 3:5 ~ 3,
                           value %in% -3:-5 ~ -3))

book_coords_7deg_prop <- text_afinn_simp %>%
  mutate(x_coord = cumsum(case_when(value == 1 ~ .78,
                             value == 2 ~ .97,
                             value == 3 ~ .43,
                             value == -1 ~ -.78,
                             value == -2 ~ -.97,
                             value == -3 ~ -.43)),
         y_coord = cumsum(case_when(value == 1 ~ .62,
                             value == 2 ~ -.22,
                             value == 3 ~ -.9,
                             value == -1 ~ .62,
                             value == -2 ~ -.22,
                             value == -3 ~ -.9)))

feather_sample1 <- sample_n(book_coords_7deg_prop, 10000, replace = TRUE, weight = prob) %>%
  mutate(color_val = row_number()) %>%
  select(word, value, color_val) %>%
  mutate(x_coord = cumsum(case_when(value == 1 ~ .78,
                             value == 2 ~ .97,
                             value == 3 ~ .43,
                             value == -1 ~ -.78,
                             value == -2 ~ -.97,
                             value == -3 ~ -.43)),
         y_coord = cumsum(case_when(value == 1 ~ .62,
                             value == 2 ~ -.22,
                             value == 3 ~ -.9,
                             value == -1 ~ .62,
                             value == -2 ~ -.22,
                             value == -3 ~ -.9)))


feather_sample2 <- sample_n(book_coords_7deg_prop, 10000, replace = TRUE, weight = prob) %>%
  mutate(color_val = row_number()) %>%
  select(word, value, color_val) %>%
  mutate(x_coord = cumsum(case_when(value == 1 ~ .78,
                             value == 2 ~ .97,
                             value == 3 ~ .43,
                             value == -1 ~ -.78,
                             value == -2 ~ -.97,
                             value == -3 ~ -.43)),
         y_coord = cumsum(case_when(value == 1 ~ .62,
                             value == 2 ~ -.22,
                             value == 3 ~ -.9,
                             value == -1 ~ .62,
                             value == -2 ~ -.22,
                             value == -3 ~ -.9)))

feather_sample3 <- sample_n(book_coords_7deg_prop, 10000, replace = TRUE, weight = prob) %>%
  mutate(color_val = row_number()) %>%
  select(word, value, color_val) %>%
  mutate(x_coord = cumsum(case_when(value == 1 ~ .78,
                             value == 2 ~ .97,
                             value == 3 ~ .43,
                             value == -1 ~ -.78,
                             value == -2 ~ -.97,
                             value == -3 ~ -.43)),
         y_coord = cumsum(case_when(value == 1 ~ .62,
                             value == 2 ~ -.22,
                             value == 3 ~ -.9,
                             value == -1 ~ .62,
                             value == -2 ~ -.22,
                             value == -3 ~ -.9)))

feather_sample4 <- sample_n(book_coords_7deg_prop, 10000, replace = TRUE, weight = prob) %>%
  mutate(color_val = row_number()) %>%
  select(word, value, color_val) %>%
  mutate(x_coord = cumsum(case_when(value == 1 ~ .78,
                             value == 2 ~ .97,
                             value == 3 ~ .43,
                             value == -1 ~ -.78,
                             value == -2 ~ -.97,
                             value == -3 ~ -.43)),
         y_coord = cumsum(case_when(value == 1 ~ .62,
                             value == 2 ~ -.22,
                             value == 3 ~ -.9,
                             value == -1 ~ .62,
                             value == -2 ~ -.22,
                             value == -3 ~ -.9)))

feather_sample5 <- sample_n(book_coords_7deg_prop, 10000, replace = TRUE, weight = prob) %>%
  mutate(color_val = row_number()) %>%
  select(word, value, color_val) %>%
  mutate(x_coord = cumsum(case_when(value == 1 ~ .78,
                             value == 2 ~ .97,
                             value == 3 ~ .43,
                             value == -1 ~ -.78,
                             value == -2 ~ -.97,
                             value == -3 ~ -.43)),
         y_coord = cumsum(case_when(value == 1 ~ .62,
                             value == 2 ~ -.22,
                             value == 3 ~ -.9,
                             value == -1 ~ .62,
                             value == -2 ~ -.22,
                             value == -3 ~ -.9)))

ggplot(data = feather_sample1, mapping = aes(x = x_coord, y = y_coord, color = "red")) +
  geom_line() +
  geom_line(data = feather_sample2) +
  geom_line(data = feather_sample3) +
  geom_line(data = feather_sample4) +
  geom_line(data = feather_sample5) +
  theme(line = element_blank(),
        text = element_blank(),
        title = element_blank(),
        panel.background = element_rect(fill = "black",
                                colour = "black",
                                size = 0.5, linetype = "solid"))

feathers <- rbind(feather_sample1, feather_sample2, feather_sample3, feather_sample4, feather_sample5)

ggplot(feather_sample1, aes(x = x_coord, y = y_coord, color = "red")) +
  geom_line() 

ggplot(feathers, aes(x = x_coord, y = y_coord, color = "red")) +
    geom_point() +
    xlim(-50, 10) +
    ylim(-50, 10)

```

```{r}
text <- gutenberg_download(36) %>%
  mutate(text = str_to_lower(text, locale = "en"))

afinn <- get_sentiments("afinn")

text_afinn <- text %>%
  unnest_tokens(output = word, input = text, token = "words") %>%
  count(word, sort = TRUE) %>%
  inner_join(afinn, by = "word") %>% 
  mutate(prob = n/sum(n),
         impact = abs(n * value)) %>%
  arrange(desc(impact)) 

sentiment <- sum(text_afinn$n*text_afinn$value)/sum(text_afinn$n)

sentiment
```

```{r}
feathers_many <- bind_rows(replicate(100, 
                    sample_n(book_coords_7deg_prop, 10000, replace = TRUE, weight = prob) %>%
  mutate(color_val = row_number()) %>%
  select(word, value, color_val) %>%
  mutate(x_coord = cumsum(case_when(value == 1 ~ .78,
                             value == 2 ~ .97,
                             value == 3 ~ .43,
                             value == -1 ~ -.78,
                             value == -2 ~ -.97,
                             value == -3 ~ -.43)),
         y_coord = cumsum(case_when(value == 1 ~ .62,
                             value == 2 ~ -.22,
                             value == 3 ~ -.9,
                             value == -1 ~ .62,
                             value == -2 ~ -.22,
                             value == -3 ~ -.9))), 
                    simplify = FALSE))

ggplot(feathers_many, aes(x = x_coord, y = y_coord)) +
  geom_point(alpha = 0.01)
```

